### ISSUE TITLE
Trie key collisions for some custom bind sequences

### ISSUE THREAD

**Issue by jstarks** [kkawakam/rustyline#509]
Here's a snippet that worked in Rustyline 7.1.0 but is broken in 8.0.0.
```
            let mut rl = rustyline::Editor::<()>::new();
            // Enable Ctrl-Backspace to delete the current word.
            rl.bind_sequence(
                rustyline::KeyEvent::new('\x08', rustyline::Modifiers::CTRL),
                rustyline::Cmd::Kill(rustyline::Movement::BackwardWord(1, rustyline::Word::Emacs)),
            );
            let line = rl.readline("> ");
```

It appears that the encoding when putting `Event` into a radix trie has some collisions, so that Ctrl-Backspace and Backspace end up with the same encoding. This causes a crash when I type backspace:

```
thread 'stdio-thread' panicked at 'multiple-keys with the same bit representation.', ***\.cargo\registry\src\github.com-1ecc6299db9ec823\radix_trie-0.2.1\src\keys.rs:76:9
stack backtrace:
   0: std::panicking::begin_panic<str>
             at ***\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:519
   1: radix_trie::keys::check_keys<rustyline::binding::Event>
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\radix_trie-0.2.1\src\keys.rs:76
   2: radix_trie::trie_node::{{impl}}::value_checked::{{closure}}<rustyline::binding::Event,rustyline::binding::EventHandler,rustyline::binding::Event>
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\radix_trie-0.2.1\src\trie_node.rs:89
   3: core::option::Option<alloc::boxed::Box<radix_trie::trie_node::KeyValue<rustyline::binding::Event, rustyline::binding::EventHandler>, alloc::alloc::Global>*>::map<alloc::boxed::Box<radix_trie::trie_node::KeyValue<rustyline::binding::Event, rustyline::bindi
             at ***\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\option.rs:487
   4: radix_trie::trie_node::TrieNode<rustyline::binding::Event, rustyline::binding::EventHandler>::value_checked<rustyline::binding::Event,rustyline::binding::EventHandler,rustyline::binding::Event>
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\radix_trie-0.2.1\src\trie_node.rs:88
   5: radix_trie::trie::{{impl}}::get::{{closure}}<rustyline::binding::Event,rustyline::binding::EventHandler,rustyline::binding::Event>
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\radix_trie-0.2.1\src\trie.rs:34
   6: core::option::Option<radix_trie::trie_node::TrieNode<rustyline::binding::Event, rustyline::binding::EventHandler>*>::and_then<radix_trie::trie_node::TrieNode<rustyline::binding::Event, rustyline::binding::EventHandler>*,rustyline::binding::EventHandler*,c
             at ***\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\option.rs:724
   7: radix_trie::Trie<rustyline::binding::Event, rustyline::binding::EventHandler>::get<rustyline::binding::Event,rustyline::binding::EventHandler,rustyline::binding::Event>
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\radix_trie-0.2.1\src\trie.rs:32
   8: rustyline::keymap::InputState::custom_binding
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\rustyline-8.0.0\src\keymap.rs:434
   9: rustyline::keymap::InputState::emacs<rustyline::tty::windows::ConsoleRawReader>
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\rustyline-8.0.0\src\keymap.rs:536
  10: rustyline::keymap::InputState::next_cmd
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\rustyline-8.0.0\src\keymap.rs:413
  11: rustyline::edit::State<tuple<>>::next_cmd<tuple<>>
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\rustyline-8.0.0\src\edit.rs:84
  12: rustyline::readline_edit<tuple<>>
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\rustyline-8.0.0\src\lib.rs:479
  13: rustyline::readline_raw<tuple<>>
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\rustyline-8.0.0\src\lib.rs:570
  14: rustyline::Editor<tuple<>>::readline_with<tuple<>>
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\rustyline-8.0.0\src\lib.rs:700
  15: rustyline::Editor<tuple<>>::readline<tuple<>>
             at ***\.cargo\registry\src\github.com-1ecc6299db9ec823\rustyline-8.0.0\src\lib.rs:676
```

**Comment by gwenn** [comment]
On Unix platform, `Backspace` == `Ctrl-H`. So at least on Unix platform, afaik, we cannot make the difference.
But we should fix it on Windows platform.
Could please confirm that you add custom bindings for both `Backspace` and Ctrl-`Backspace` ?
Thanks.

**Comment by gwenn** [comment]
Could you please give #511 a try ?
Thanks.

**Comment by gwenn** [comment]
Version 8.1.0 released
